/**
 * Creating a sidebar enables you to:
 - Create an ordered group of docs
 - Render a sidebar in the docs site
 - List of frontmatter fields that define the sidebar:
   - sidebar_label: sidebar label (string)
   - sidebar_position: position of the doc in the sidebar (number)
   - custom_edit_url: overrides the docs.editUrl value for this doc (string)
   - hide_title: Hide the title of the doc (boolean)
   - hide_table_of_contents: Hide the table of contents (boolean)
   - keywords: keywords for the doc for better SEO (string[]). E.g. `keywords: ['docusaurus', 'hello']`
 */

const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;